name: Publish to Microsoft Store

on:
    workflow_call:

jobs:
    windows-store:
        name: Publish to MacOS # no app store
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache bundle dependencies
              uses: actions/cache@v3
              with:
                  path: vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: ${{ runner.os }}-gems-

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0

            - name: Download bundle dependencies
              run: |
                  gem install bundler
                  bundle config path vendor/bundle
                  bundle install

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.22.2"

            - name: Delete Podfile.lock
              run: rm macos/Podfile.lock

            - name: Download pub dependencies
              run: flutter pub get

            - name: Pod repo update
              working-directory: macos
              run: pod install --repo-update

            - name: Build MacOS via Flutter
              run: flutter build macos --release

            - name: Upload build to workflow run
              uses: actions/upload-artifact@v1
              with:
                  name: Spheroscopic-macOS
                  path: ${{ github.workspace }}/build/macos/x64/runner/Release

            - name: Build DMG
              uses: L-Super/create-dmg-actions@v1.0.2
              with:
                  dmg_name: "Spheroscopic-${{ needs.version-update.outputs.version }}"
                  src_dir: "${{ github.workspace }}/build/macos/x64/runner/Release/Spheroscopic.app"

            - name: Upload build to Github Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ needs.version-update.outputs.version }}
                  files: "Spheroscopic-${{ needs.version-update.outputs.version }}.dmg"
