name: Build on version commit

on:
    push:
        branches:
            - main

jobs:
    version-update:
        if: contains(github.event.head_commit.message, 'r-v')
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.extract-version.outputs.version }}

        steps:
            - uses: actions/checkout@v4

            - name: Extract version
              id: extract-version
              run: |
                  version=$(echo "${{ github.event.head_commit.message }}" | sed 's/r-v/v/')
                  echo "::set-output name=version::$version"

            - name: Run build
              run: |
                  echo "Running build for version ${{ steps.extract-version.outputs.version }}"
                  # Your build command here, e.g., ./build.sh ${{ steps.extract-version.outputs.version }}

    publish-macos:
        uses: ./.github/workflows/publish-macos.yml
        needs: [version-update]
        secrets: inherit

    #publish-linux:
    #uses: ./.github/workflows/publish-linux.yml
    #needs: [version-update]
    #secrets: inherit

    publish-windows:
        uses: ./.github/workflows/publish-windows.yml
        needs: [version-update]
        secrets: inherit
